spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://192.168.20.130:9411

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.20.130:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info